// Generated by gencpp from file kanu_pkg/DistServiceMessage.msg
// DO NOT EDIT!


#ifndef KANU_PKG_MESSAGE_DISTSERVICEMESSAGE_H
#define KANU_PKG_MESSAGE_DISTSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <kanu_pkg/DistServiceMessageRequest.h>
#include <kanu_pkg/DistServiceMessageResponse.h>


namespace kanu_pkg
{

struct DistServiceMessage
{

typedef DistServiceMessageRequest Request;
typedef DistServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DistServiceMessage
} // namespace kanu_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kanu_pkg::DistServiceMessage > {
  static const char* value()
  {
    return "81921970ef6bbdc458ce6f038299ceae";
  }

  static const char* value(const ::kanu_pkg::DistServiceMessage&) { return value(); }
};

template<>
struct DataType< ::kanu_pkg::DistServiceMessage > {
  static const char* value()
  {
    return "kanu_pkg/DistServiceMessage";
  }

  static const char* value(const ::kanu_pkg::DistServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::kanu_pkg::DistServiceMessageRequest> should match
// service_traits::MD5Sum< ::kanu_pkg::DistServiceMessage >
template<>
struct MD5Sum< ::kanu_pkg::DistServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kanu_pkg::DistServiceMessage >::value();
  }
  static const char* value(const ::kanu_pkg::DistServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kanu_pkg::DistServiceMessageRequest> should match
// service_traits::DataType< ::kanu_pkg::DistServiceMessage >
template<>
struct DataType< ::kanu_pkg::DistServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::kanu_pkg::DistServiceMessage >::value();
  }
  static const char* value(const ::kanu_pkg::DistServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kanu_pkg::DistServiceMessageResponse> should match
// service_traits::MD5Sum< ::kanu_pkg::DistServiceMessage >
template<>
struct MD5Sum< ::kanu_pkg::DistServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kanu_pkg::DistServiceMessage >::value();
  }
  static const char* value(const ::kanu_pkg::DistServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kanu_pkg::DistServiceMessageResponse> should match
// service_traits::DataType< ::kanu_pkg::DistServiceMessage >
template<>
struct DataType< ::kanu_pkg::DistServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::kanu_pkg::DistServiceMessage >::value();
  }
  static const char* value(const ::kanu_pkg::DistServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KANU_PKG_MESSAGE_DISTSERVICEMESSAGE_H
