# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kanu_pkg/Markers.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kanu_pkg.msg

class Markers(genpy.Message):
  _md5sum = "233e0e9eb1ef4e1d8dc45028904252ed"
  _type = "kanu_pkg/Markers"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """MarkerInfo[] marker_info
================================================================================
MSG: kanu_pkg/MarkerInfo
uint32 id
float32[] rvec
float32[] tvec
float32 center_x
float32 center_y"""
  __slots__ = ['marker_info']
  _slot_types = ['kanu_pkg/MarkerInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       marker_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Markers, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.marker_info is None:
        self.marker_info = []
    else:
      self.marker_info = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.marker_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.marker_info:
        _x = val1.id
        buff.write(_get_struct_I().pack(_x))
        length = len(val1.rvec)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.rvec))
        length = len(val1.tvec)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.tvec))
        _x = val1
        buff.write(_get_struct_2f().pack(_x.center_x, _x.center_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.marker_info is None:
        self.marker_info = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.marker_info = []
      for i in range(0, length):
        val1 = kanu_pkg.msg.MarkerInfo()
        start = end
        end += 4
        (val1.id,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.rvec = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.tvec = s.unpack(str[start:end])
        _x = val1
        start = end
        end += 8
        (_x.center_x, _x.center_y,) = _get_struct_2f().unpack(str[start:end])
        self.marker_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.marker_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.marker_info:
        _x = val1.id
        buff.write(_get_struct_I().pack(_x))
        length = len(val1.rvec)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.rvec.tostring())
        length = len(val1.tvec)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.tvec.tostring())
        _x = val1
        buff.write(_get_struct_2f().pack(_x.center_x, _x.center_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.marker_info is None:
        self.marker_info = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.marker_info = []
      for i in range(0, length):
        val1 = kanu_pkg.msg.MarkerInfo()
        start = end
        end += 4
        (val1.id,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.rvec = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.tvec = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        _x = val1
        start = end
        end += 8
        (_x.center_x, _x.center_y,) = _get_struct_2f().unpack(str[start:end])
        self.marker_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
