(cl:defpackage kanu_pkg-srv
  (:use )
  (:export
   "DISTSERVICEMESSAGE"
   "<DISTSERVICEMESSAGE-REQUEST>"
   "DISTSERVICEMESSAGE-REQUEST"
   "<DISTSERVICEMESSAGE-RESPONSE>"
   "DISTSERVICEMESSAGE-RESPONSE"
  ))

